name: Keep Supabase Alive

on:
  schedule:
    # Berjalan setiap hari Senin dan Kamis jam 00:00 UTC
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # Memungkinkan untuk di-run manual jika ingin tes

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/data_peserta?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"